### ISSUE TITLE
Flush command breaks when user preferences disabled 

### ISSUE THREAD

**Issue by okolimar** [EliotBerriot/django-dynamic-preferences#122] opened 2017-11-06 16:53 UTC
Some migrations reference user preference model so it is not possible to have user preferences model not installed and run for example manage.py flush

**Comment by EliotBerriot** [comment] 2017-11-06 17:42
Thanks for the report, I'm closing as a duplicate of #83 , but we can of course continue the discussion here :)

**Closed by EliotBerriot** 2017-11-06 17:42 UTC
